version: 0.1 b{build}
image: Visual Studio 2022
build_script:
- cmd: >-
    dotnet --info

    dotnet restore

    dotnet build -c Release

    dotnet pack --include-symbols --include-source -c Release

    dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -c Release
artifacts:
- path: bin\Release\net6.0\win-x64\publish\Hybrid7z.exe
  name: Executable
- path: bin\Release\net6.0\win-x64\publish\Hybrid7z.pdb
  name: Debug symbol database
